# Site settings
author: John M. Stassen
title: Stass Blog
header-img: img/home-bg.png
email: john.stassen@gmail.com
copyright_name: John M. Stassen
description: > # this means to ignore newlines until "baseurl:"
  thoughts and reflections - work in progress
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jmstassen

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
